from krcg import vtes


def test_init():
    assert vtes.VTES.search_dimensions() == {
        "bonus": {"bleed", "intercept", "trifle", "stealth", "votes", "capacity"},
        "capacity": {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
        "clan": {
            "none",
            "osebo",
            "lasombra",
            "tremere",
            "harbinger of skulls",
            "blood brother",
            "toreador",
            "giovanni",
            "ahrimane",
            "akunanse",
            "brujah",
            "assamite",
            "follower of set",
            "brujah antitribu",
            "guruhi",
            "toreador antitribu",
            "tzimisce",
            "malkavian",
            "gangrel",
            "gangrel antitribu",
            "daughter of cacophony",
            "salubri antitribu",
            "samedi",
            "baali",
            "ravnos",
            "kiasyd",
            "nagaraja",
            "pander",
            "ventrue antitribu",
            "nosferatu antitribu",
            "malkavian antitribu",
            "tremere antitribu",
            "nosferatu",
            "ishtarri",
            "ventrue",
            "gargoyle",
            "salubri",
            "avenger",
            "true brujah",
            "visionary",
            "defender",
            "caitiff",
            "abomination",
            "martyr",
            "innocent",
            "judge",
            "redeemer",
        },
        "discipline": {
            # general groups
            "none",
            "mono",
            "multi",
            "choice",
            "combo",
            # not disciplines
            "striga",
            "maleficia",
            "flight",
            "jud",
            "vin",
            "inn",
            "mar",
            "def",
            "red",
            "ven",
            # normal list
            "abo",
            "ani",
            "aus",
            "cel",
            "chi",
            "dai",
            "dem",
            "dom",
            "for",
            "mel",
            "myt",
            "nec",
            "obe",
            "obf",
            "obt",
            "pot",
            "pre",
            "pro",
            "qui",
            "san",
            "ser",
            "spi",
            "tem",
            "tha",
            "thn",
            "val",
            "vic",
            "vis",
            "ABO",
            "ANI",
            "AUS",
            "CEL",
            "CHI",
            "DAI",
            "DEM",
            "DOM",
            "FOR",
            "MEL",
            "MYT",
            "NEC",
            "OBE",
            "OBF",
            "OBT",
            "POT",
            "PRE",
            "PRO",
            "QUI",
            "SAN",
            "SER",
            "SPI",
            "TEM",
            "THA",
            "THN",
            "VAL",
            "VIC",
            "VIS",
        },
        "group": {1, 2, 3, 4, 5, 6},
        "sect": {"sabbat", "camarilla", "anarch", "laibon", "independent"},
        "title": {
            "justicar",
            "inner circle",
            "kholo",
            "baron",
            "prince",
            "cardinal",
            "regent",
            "magaji",
            "primogen",
            "archbishop",
            "priscus",
            "bishop",
            "imperator",
            "1 vote",
            "2 votes",
        },
        "city": {
            "london",
            "melbourne",
            "birmingham",
            "montreal",
            "nairobi",
            "mexico city",
            "pittsburgh",
            "taipei",
            "seattle",
            "chicago",
            "atlanta",
            "washington, d.c.",
            "addis ababa",
            "brussels",
            "copenhagen",
            "fortaleza",
            "manila",
            "new york",
            "stockholm",
            "budapest",
            "detroit",
            "boston",
            "prague",
            "columbus",
            "buenos aires",
            "rome",
            "cairo",
            "berlin",
            "paris",
            "dublin",
            "cordoba",
            "toronto",
            "miami",
            "milan",
            "chicago ",
            "mannheim",
            "rio de janeiro",
            "geneva",
            "dallas",
            "versailles",
            "monaco",
            "barcelona",
            "los angeles",
            "amsterdam",
            "istanbul",
            "houston",
            "lisbon",
            "glasgow",
            "frankfurt",
            "port-au-prince",
            "canberra",
            "philadelphia",
            "aragon",
            "strasbourg",
            "milwaukee",
            "cape town",
            "guadalajara",
            "cleveland",
            "athens",
            "sydney",
            "rotterdam",
            "san diego",
            "guatemala city",
        },
        "trait": {
            "sterile",
            "black hand",
            "slave",
            "red list",
            "seraph",
            "infernal",
            "scarce",
        },
        "type": {
            "equipment",
            "library",
            "action",
            "reaction",
            "combat",
            "power",
            "master",
            "event",
            "ally",
            "action modifier",
            "political action",
            "retainer",
            "conviction",
            "vampire",
            "crypt",
            "imbued",
        },
        "set": {
            "1996 Promo",
            "2003 Tournament promo",
            "2004 promo",
            "2005 Storyline promo",
            "2005 Tournament promo",
            "2006 Championship promo",
            "2006 EC Tournament promo",
            "2006 Storyline promo",
            "2006 Tournament promo",
            "2007 Promo",
            "2008 Storyline promo",
            "2008 Tournament promo",
            "2009 Tournament / Storyline promo",
            "2010 Storyline promo",
            "2015 Storyline Rewards",
            "2018 Humble Bundle",
            "2019 AC Promo",
            "2019 ACC Promo",
            "2019 DriveThruCards Promo",
            "2019 EC Promo",
            "2019 Grand Prix Promo",
            "2019 NAC Promo",
            "2019 Promo",
            "2019 Promo Pack 1",
            "2019 SAC Promo",
            "2020 GP Promo",
            "2020 Promo Pack 2",
            "Anarch Unbound",
            "Anarchs",
            "Anarchs promo",
            "Ancient Hearts",
            "Anthology",
            "Black Hand",
            "Black Hand promo",
            "Blood Shadowed Court",
            "Bloodlines",
            "Bloodlines promo",
            "Camarilla Edition",
            "Camarilla Edition promo",
            "Danse Macabre",
            "Dark Sovereigns",
            "Ebony Kingdom",
            "Fall 2002 Storyline promo",
            "Fall 2004 Storyline promo",
            "Fifth Edition",
            "Final Nights",
            "Final Nights promo",
            "First Blood",
            "Gehenna",
            "Gehenna promo",
            "Heirs to the Blood",
            "Jyhad",
            "Keepers of Tradition",
            "Kindred Most Wanted",
            "Kindred Most Wanted promo",
            "Legacies of Blood",
            "Legacies of Blood promo",
            "Lords of the Night",
            "Lost Kindred",
            "Nights of Reckoning",
            "Print on Demand",
            "Prophecies league promo",
            "Sabbat",
            "Sabbat Preconstructed",
            "Sabbat War",
            "Sabbat War promo",
            "Summer 2003 Storyline promo",
            "Sword of Caine",
            "Sword of Caine promo",
            "Tenth Anniversary",
            "The Unaligned",
            "Third Edition",
            "Third Edition promo",
            "Twenty-Fifth Anniversary",
            "Twilight Rebellion",
            "V5 Polish Edition promo",
            "Vampire: The Eternal Struggle",
            "Winter 2002 Storyline promo",
        },
        "rarity": {"Common", "Rare", "Uncommon", "Vampire"},
        "precon": {
            "2018 Humble Bundle: Humble Bundle",
            "Anarchs: Anarch Barons",
            "Anarchs: Anarch Gang",
            "Anarchs: Gangrel",
            "Anthology: EC Berlin Edition",
            "Black Hand: Malkavian antitribu",
            "Black Hand: Nosferatu antitribu",
            "Black Hand: Toreador antitribu",
            "Black Hand: Tremere antitribu",
            "Camarilla Edition: Brujah",
            "Camarilla Edition: Malkavian",
            "Camarilla Edition: Nosferatu",
            "Camarilla Edition: Toreador",
            "Camarilla Edition: Tremere",
            "Camarilla Edition: Ventrue",
            "Fifth Edition: Malkavian",
            "Fifth Edition: Nosferatu",
            "Fifth Edition: Toreador",
            "Fifth Edition: Tremere",
            "Fifth Edition: Ventrue",
            "Final Nights: Assamite",
            "Final Nights: Followers of Set",
            "Final Nights: Giovanni",
            "Final Nights: Ravnos",
            "First Blood: Malkavian",
            "First Blood: Nosferatu",
            "First Blood: Toreador",
            "First Blood: Tremere",
            "First Blood: Ventrue",
            "Heirs to the Blood: Gargoyles",
            "Heirs to the Blood: Kiasyd",
            "Heirs to the Blood: Reprint Bundle 1",
            "Heirs to the Blood: Reprint Bundle 2",
            "Heirs to the Blood: Salubri antitribu",
            "Heirs to the Blood: Samedi",
            "Keepers of Tradition: Brujah",
            "Keepers of Tradition: Malkavian",
            "Keepers of Tradition: Reprint Bundle 1",
            "Keepers of Tradition: Reprint Bundle 2",
            "Keepers of Tradition: Toreador",
            "Keepers of Tradition: Ventrue",
            "Kindred Most Wanted: Alastors",
            "Kindred Most Wanted: Anathema",
            "Kindred Most Wanted: Baali",
            "Kindred Most Wanted: Gangrel antitribu",
            "Legacies of Blood: Akunanse",
            "Legacies of Blood: Guruhi",
            "Legacies of Blood: Ishtarri",
            "Legacies of Blood: Osebo",
            "Lords of the Night: Assamite",
            "Lords of the Night: Followers of Set",
            "Lords of the Night: Giovanni",
            "Lords of the Night: Ravnos",
            "Print on Demand: DriveThruCards",
            "Sabbat Preconstructed: Den of Fiends",
            "Sabbat Preconstructed: Libertine Ball",
            "Sabbat Preconstructed: Pact with Nephandi",
            "Sabbat Preconstructed: Parliament of Shadows",
            "Sabbat War: Brujah antitribu",
            "Sabbat War: Lasombra",
            "Sabbat War: Tzimisce",
            "Sabbat War: Ventrue antitribu",
            "Tenth Anniversary: Tin A",
            "Tenth Anniversary: Tin B",
            "Third Edition: Brujah antitribu",
            "Third Edition: Malkavian antitribu",
            "Third Edition: Tremere antitribu",
            "Third Edition: Tzimisce",
        },
        "artist": {
            "Aaron Acevedo",
            "Aaron Voss",
            "Abrar Ajmal",
            "Alan Rabinowitz",
            "Albrecht",
            "Alejandro Colucci",
            "Alejandro F. Giraldo",
            "Alexander Dunnigan",
            "Amy Weber",
            "Amy Wilkins",
            "Andre Gates",
            "Andrew Bates",
            "Andrew Hepworth",
            "Andrew Robinson",
            "Andrew Trabbold",
            "André Freitas",
            "Anna Christenson",
            "Anna Evertsdotter",
            "Anson Maddocks",
            "Ari Targownik",
            "Arkady Roytman",
            "Arthur Roberg",
            "Ash Arnett",
            "Atilio Gambedotti",
            "Attila Adorjany",
            "August Bøgedal Hansen",
            "Avery Butterworth",
            "Becky Cloonan",
            "Becky Jollensten",
            "Ben Mirabelli",
            "Beth Trott",
            "Bob Stevlic",
            "Brad Williams",
            "Brian Ashmore",
            "Brian Horton",
            "Brian LeBlanc",
            "Brian Miskelley",
            "Brian Snoddy",
            "Britt Martin",
            "Bryon Wackwitz",
            "Caleb Cleaveland",
            "Carmen Cornet",
            "Chad Michael Ward",
            "Chet Masters",
            "Chris McLoughlin",
            "Chris Richards",
            "Chris Stevens",
            "Christel Espenkrona",
            "Christopher Rush",
            "Christopher Shy",
            "Cliff Nielson",
            "Clint Langley",
            "Corey Macourek",
            "Cos Koniotis",
            "Craig Grant",
            "Craig Maher",
            "D. Fryendall",
            "Dan Frazier",
            "Dan Smith",
            "Daniel Gelon",
            "Darryl Elliott",
            "Dave Leri",
            "Dave Roach",
            "Dave Seeley",
            "David Day",
            "David Fooden",
            "David Ho",
            "David Kimmel",
            "Dennis Calero",
            "Diana Vick",
            "Doug Alexander",
            "Doug Gregory",
            "Doug Stambaugh",
            "Douglas Shuler",
            "Drew Tucker",
            "Durwin Talon",
            "E.M. Gist",
            "Ed Tadem",
            "Edward Beard, Jr.",
            "Efrem Palacios",
            "Elli Adams",
            "Eric Deschamps",
            "Eric Kim",
            "Eric LaCombe",
            "Eric Lofgren",
            "Erica Danell",
            "Felipe Gaona",
            "Francesc Grimalt",
            "Franz Vohwinkel",
            "Fred Harper",
            "Fred Hooper",
            "Gary Chatterton",
            "Gary Leach",
            "Ginés Quiñonero-Santiago",
            "Glen Osterberger",
            "Grant Garvin",
            "Grant Goleash",
            "Greg Boychuk",
            "Greg Loudon",
            "Greg Simanson",
            "Grzegorz Bobrowski",
            "Gábor Németh",
            "Hannibal King",
            "Harold Arthur McNeill",
            "Heather Hudson",
            "Heather J. McKinney",
            "Heather V. Kreiter",
            "Ian Hernaiz",
            "Imaginary Friends Studios",
            "J Frederick Y",
            "Jake Smidt",
            "James Allen Higgins",
            "James Richardson",
            "James Stowe",
            "Jami Waggoner",
            "Jared Smith",
            "Jarkko Suvela",
            "Jason Alexander Behnke",
            "Jason Brubaker",
            "Javier Santos",
            'Jeff "el jefe" Holt',
            "Jeff Klimek",
            "Jeff Laubenstein",
            "Jeff Menges",
            "Jeff Miracola",
            "Jeff Rebner",
            "Jenny Frison",
            "Jeremy C. Bills",
            "Jeremy McHugh",
            "Jesús Ybarzábal",
            "Jim Di Bartolo",
            "Jim Nelson",
            "Jim Pavelec",
            "Joe Slucher",
            "Joe Ziolkowski",
            "Joel Biske",
            "John Bolton",
            "John Bridges",
            "John Kent",
            "John Matson",
            "John McCrea",
            "John Scotello",
            "John Van Fleet",
            "Josh Timbrook",
            "Juan Antonio Serrano Garcia",
            "Juan Calle",
            "Julian Jackson",
            "Julie Collins",
            "Justin Norman",
            "Kaja Foglio",
            "Kari Christensen",
            "Karl Waller",
            "Katie McCaskill",
            "Kelly Howlett",
            "Ken Meyer, Jr.",
            "Kent Williams",
            "Kevin McCann",
            "Kieran Yanner",
            "Kyri Koniotis",
            "L. A. Williams",
            "Laia López Tubau",
            "Larry MacDougall",
            "Lawrence Snelly",
            "Lee Carter",
            "Lee Dotson",
            "Lee Fields",
            "Leif Jones",
            "Liz Danforth",
            "Marco Marzoni",
            "Marco Nelor",
            "Margaret Organ-Kean",
            "Marian Churchland",
            "Mark Kelly",
            "Mark Nelson",
            "Mark Poole",
            "Mark Tedin",
            "Martín de Diego Sábada",
            "Mathias Kollros",
            "Matias Tapia",
            "Matt Cavotta",
            "Matt Dixon",
            "Matt Smith",
            "Matt Wilson",
            "Matthew Mitchell",
            "Max Shade Fellwalker",
            "Melissa Benson",
            "Melissa Uran",
            "Michael Astrachan",
            "Michael Dixon",
            "Michael Gaydos",
            "Michael Weaver",
            "Mick Bertilorenzi",
            "Mike Chaney",
            "Mike Danza",
            "Mike Dringenberg",
            "Mike Huddleston",
            "Mike Raabe",
            "Mirko Falloni",
            "Mitch Mueller",
            "Monte Moore",
            "Newel Anderson",
            "Nicola Leonard",
            'Nicolas "Dimple" Bigot',
            "Nicole Cardiff",
            "Nigel Sade",
            "Nilson",
            "Noah Hirka",
            "Noora Hirvonen",
            "Né Né Thomas",
            "Oliver Meinerding",
            "Oscar Salcedo",
            "Pat Loboyko",
            "Pat Morrissey",
            "Patrick Kochakji",
            "Patrick Lambert",
            "Patrick McEvoy",
            "Paul Ballard",
            "Paul Tobin",
            "Pete Burges",
            "Pete Venters",
            "Peter Bergting",
            "Peter Kim",
            "Peter Morbacher",
            "Phil Wohr",
            "Phillip Hilliker",
            "Phillip Tan",
            "Quinton Hoover",
            "Randy Asplund",
            "Randy Gallegos",
            "Rebecca Guay",
            "Riccardo Fabiani",
            "Richard Kane Ferguson",
            "Richard Thomas",
            "Rick Berry",
            "Rick O'Brien",
            "Rik Martin",
            "Rob Alexander",
            "Robert McNeill",
            "Robin Chyo",
            "Roel Wielinga",
            "Roger Raupp",
            "Ron Lemon",
            "Ron Spencer",
            "Ron Van Halen",
            "Rubén Bravo",
            "Samuel Araya",
            "Sandra Chang-Adair",
            "Sandra Everingham",
            "Satyr",
            "Scott Fischer",
            "Scott Kirschner",
            "Scott M. Bakal",
            "Shane Coppage",
            "Steve Casper",
            "Steve Eidson",
            "Steve Ellis",
            "Steve Prescott",
            "Stuart Beel",
            "Stuart Sayger",
            "Sue Ann Harkey",
            "Susan Van Camp",
            "Talon Dunning",
            "Ted Naifeh",
            "Terese Nielsen",
            "Thea Maia",
            "Theodore Black",
            "Thomas Baxa",
            "Thomas Denmark",
            "Thomas Manning",
            "Thomas Nairb",
            "Tim Bradstreet",
            "Tom Biondillo",
            "Tom Duncan",
            "Tom Gianni",
            "Tom Wänerstrand",
            'Tomáš "zelgaris" Zahradníček',
            "Tony Harris",
            "Tony Shasteen",
            "Torstein Nordstrand",
            "Travis Ingram",
            "Trevor Claxton",
            "UDON",
            "Vatche Mavlian",
            "Veronica Jones",
            "Vince Locke",
            "Warren Mahy",
            "Will Simpson",
            "William O'Connor",
            "Zina Saunders",
            "matrix von z",
            "rk post",
        },
    }


def test_fuzzy_match():
    assert "enchant kidnred" in vtes.VTES
    assert vtes.VTES["enchant kidnred"].name == "Enchant Kindred"


def test_search():
    # some tricky cards test (add cards for NR tests)
    # providing a stealth action does not register as "stealth" bonus
    assert vtes.VTES["Tracker's Mark"] in vtes.VTES.search(bonus=["intercept"])
    assert vtes.VTES["Tracker's Mark"] not in vtes.VTES.search(bonus=["stealth"])
    assert vtes.VTES["Brainwash"] not in vtes.VTES.search(bonus=["stealth"])


def test_vekn():
    vtes.VTES.load_from_vekn()
    assert len(vtes.VTES) >= 3788
    assert set(vtes.VTES[100001].__getstate__().keys()) == {
        "_i18n",
        "_name",
        "artists",
        "card_text",
        "id",
        "name",
        "pool_cost",
        "rulings",
        "sets",
        "types",
        "url",
    }
