# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: |
          uv sync --group dev
      - name: Format check
        run: |
          uv run ruff format --check .
      - name: Lint
        run: |
          uv run ruff check
      - name: Test
        env:
          LOCAL_CARDS: 1
        run: |
          uv run coverage run -m pytest
          uv run coverage xml
      - name: Upload coverage to Codacy
        if: github.event_name == 'push'
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          uv run python-codacy-coverage -r coverage.xml
